export const CONTACT_SUBMIT_REQUEST = 'CONTACT_SUBMIT_REQUEST'
export const CONTACT_SUBMIT_SUCCESS = 'CONTACT_SUBMIT_SUCCESS'
export const CONTACT_SUBMIT_FAIL = 'CONTACT_SUBMIT_FAIL'
export const CONTACT_SUBMIT_RESET = 'CONTACT_SUBMIT_RESET'

export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST'
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS'
export const CONTACT_LIST_FAIL = 'CONTACTORDER_LIST_FAIL'