export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const MENPRODUCT_LIST_REQUEST = 'MENPRODUCT_LIST_REQUEST'
export const MENPRODUCT_LIST_SUCCESS = 'MENPRODUCT_LIST_SUCCESS'
export const MENPRODUCT_LIST_FAIL = 'MENPRODUCT_LIST_FAIL'

export const WOMENPRODUCT_LIST_REQUEST = 'WOMENPRODUCT_LIST_REQUEST'
export const WOMENPRODUCT_LIST_SUCCESS = 'WOMENPRODUCT_LIST_SUCCESS'
export const WOMENPRODUCT_LIST_FAIL = 'WOMENPRODUCT_LIST_FAIL'

export const WOMENPRODUCT_DETAILS_REQUEST = 'WOMENPRODUCT_DETAILS_REQUEST'
export const WOMENPRODUCT_DETAILS_SUCCESS = 'WOMENPRODUCT_DETAILS_SUCCESS'
export const WOMENPRODUCT_DETAILS_FAIL = 'WOMENPRODUCT_DETAILS_FAIL'

export const MENPRODUCT_DETAILS_REQUEST = 'MENPRODUCT_DETAILS_REQUEST'
export const MENPRODUCT_DETAILS_SUCCESS = 'MENPRODUCT_DETAILS_SUCCESS'
export const MENPRODUCT_DETAILS_FAIL = 'MENPRODUCT_DETAILS_FAIL'

export const MENPRODUCT_DELETE_REQUEST = 'MENPRODUCT_DELETE_REQUEST'
export const MENPRODUCT_DELETE_SUCCESS = 'MENPRODUCT_DELETE_SUCCESS'
export const MENPRODUCT_DELETE_FAIL = 'MENPRODUCT_DELETE_FAIL'


export const WOMENPRODUCT_DELETE_REQUEST = 'WOMENPRODUCT_DELETE_REQUEST'
export const WOMENPRODUCT_DELETE_SUCCESS = 'WOMENPRODUCT_DELETE_SUCCESS'
export const WOMENPRODUCT_DELETE_FAIL = 'WOMENPRODUCT_DELETE_FAIL'


export const MENPRODUCT_CREATE_REQUEST = 'MENPRODUCT_CREATE_REQUEST'
export const MENPRODUCT_CREATE_SUCCESS = 'MENPRODUCT_CREATE_SUCCESS'
export const MENPRODUCT_CREATE_FAIL = 'MENPRODUCT_CREATE_FAIL'
export const MENPRODUCT_CREATE_RESET = 'MENPRODUCT_CREATE_RESET'

export const WOMENPRODUCT_CREATE_REQUEST = 'WOMENPRODUCT_CREATE_REQUEST'
export const WOMENPRODUCT_CREATE_SUCCESS = 'WOMENPRODUCT_CREATE_SUCCESS'
export const WOMENPRODUCT_CREATE_FAIL = 'WOMENPRODUCT_CREATE_FAIL'
export const WOMENPRODUCT_CREATE_RESET = 'WOMENPRODUCT_CREATE_RESET'

export const MENPRODUCT_UPDATE_REQUEST = 'MENPRODUCT_UPDATE_REQUEST'
export const MENPRODUCT_UPDATE_SUCCESS = 'MENPRODUCT_UPDATE_SUCCESS'
export const MENPRODUCT_UPDATE_FAIL = 'MENPRODUCT_UPDATE_FAIL'
export const MENPRODUCT_UPDATE_RESET = 'MENPRODUCT_UPDATE_RESET'

export const WOMENPRODUCT_UPDATE_REQUEST = 'WOMENPRODUCT_UPDATE_REQUEST'
export const WOMENPRODUCT_UPDATE_SUCCESS = 'WOMENPRODUCT_UPDATE_SUCCESS'
export const WOMENPRODUCT_UPDATE_FAIL = 'WOMENPRODUCT_UPDATE_FAIL'
export const WOMENPRODUCT_UPDATE_RESET = 'WOMENPRODUCT_UPDATE_RESET'

export const MENPRODUCT_CREATE_REVIEW_REQUEST = 'MENPRODUCT_CREATE_REVIEW_REQUEST'
export const MENPRODUCT_CREATE_REVIEW_SUCCESS = 'MENPRODUCT_CREATE_REVIEW_SUCCESS'
export const MENPRODUCT_CREATE_REVIEW_FAIL = 'MENPRODUCT_CREATE_REVIEW_FAIL'
export const MENPRODUCT_CREATE_REVIEW_RESET = 'MENPRODUCT_CREATE_REVIEW_RESET'

export const WOMENPRODUCT_CREATE_REVIEW_REQUEST = 'WOMENPRODUCT_CREATE_REVIEW_REQUEST'
export const WOMENPRODUCT_CREATE_REVIEW_SUCCESS = 'WOMENPRODUCT_CREATE_REVIEW_SUCCESS'
export const WOMENPRODUCT_CREATE_REVIEW_FAIL = 'WOMENPRODUCT_CREATE_REVIEW_FAIL'
export const WOMENPRODUCT_CREATE_REVIEW_RESET = 'WOMENPRODUCT_CREATE_REVIEW_RESET'